[workspace]
members = [
    "crates/bvh-kernels",
    "crates/bvh-trace-kernels",
    "crates/collection-kernels",
    "crates/graph-kernels",
    "crates/octree-kernels",
    "crates/search-kernels",
    "crates/spatial-kernels",
    "crates/statistics-kernels",
]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT"
rust-version = "1.85"
