name: Public Contract

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  public-contract:
    uses: moritzbrantner/reusable-workflows/.github/workflows/public-contract-validation.yml@e89be9c125880081ebcec54095d2823a15365798
    with:
      install_mode: none
